theme: jekyll-theme-leap-day
title: Diceware Password Generator
description: Diceware password generator with multiple variations; written in Python.
url: https://code.22digital.tech/diceware-password-generator/
publisher: Justin Hartman
lang: en_GB
author:
  name: Justin Hartman
  email: justin@hartman.me
  uri: http://justin.hartman.me
  image: https://avatars3.githubusercontent.com/u/717118?s=460&v=4
twitter:
  username: justinhartman
facebook:
  admins: 566420412
logo: https://avatars3.githubusercontent.com/u/717118?s=460&v=4
social:
  name: Justin Hartman
  links:
    - https://twitter.com/justinhartman
    - https://www.facebook.com/justin.hartman.me
    - https://www.linkedin.com/in/justinhartman
    - https://plus.google.com/+iamjustinhartman
    - https://github.com/justinhartman
    - https://www.instagram.com/justin.hartman
    - https://www.pinterest.com/iamjustinhartman
disqus: diceware-password-generator
google_analytics: UA-100937492-3
webmaster_verifications:
  google: 1234 # https://www.google.com/webmasters/tools/home?hl=en&pli=1
  bing: 1234 # https://www.bing.com/webmaster/home/mysites
  yandex: 1234 # https://webmaster.yandex.com/sites/
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-include-cache
# github: [metadata]
show_downloads: true
