theme: jekyll-theme-midnight
title: Diceware Password Generator
description: Diceware password generator with multiple variations; written in Python.
# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars3.githubusercontent.com/u/717118?s=460&v=4
# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: justin@hartman.me
  facebook: justin.hartman.me
  flickr:
  github: justinhartman
  instagram:
  linkedin: justinhartman
  pinterest: iamjustinhartman
  rss: rss # just type anything here for a working RSS icon
  twitter: justinhartman
  stackoverflow: users/1322242/justinhartman # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: diceware-password-generator
# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-100937492-3
