#!/bin/sh
curl -o words https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt
curl -o words-vorvig http://norvig.com/ngrams/count_1w.txt
curl -o words-short-memorable https://www.eff.org/files/2016/09/08/eff_short_wordlist_1.txt
curl -o words-short-edit https://www.eff.org/files/2016/09/08/eff_short_wordlist_2_0.txt
curl -o words-beale http://world.std.com/%7Ereinhold/beale.wordlist.asc
exit
